version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        volumes:
            - ./db-api:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: pokedex
        ports:
            - '5433:5433'

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: root@example.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - '5050:80'
        depends_on:
            - postgres

    backend:
        build:
            context: ./backend
        container_name: backend
        restart: always
        environment:
            PORT: 3000
            JWT_SECRET: 'secret'
            HOST: '0.0.0.0'
            DATABASE_URL: 'postgresql://root:root@postgres:5433/pokedex?schema=public'
            APP_URL: 'http://127.0.0.1:3001'
            TIME_ZONE: 'America/Sao_Paulo'
            APP_NAME: 'Pokedex'
        ports:
            - '3000:3000'
        depends_on:
            - postgres

    frontend:
        build:
            context: ./frontend
        container_name: frontend
        restart: always
        environment:
            VITE_API_URL: 'http://127.0.0.1:3000'
        ports:
            - '3001:3001'
        depends_on:
            - backend
